# Generated by Django 5.0.4 on 2024-04-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutText',
            new_name='ContactText',
        ),
    ]
