# Generated by Django 4.2.9 on 2024-04-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(default='', max_length=200)),
                ('descText', models.CharField(blank=True, max_length=1024)),
                ('imagePath', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playName', models.CharField(default='', max_length=200)),
                ('playDescription', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=37)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExhibitPage.exhibitdata')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExhibitPage.play')),
            ],
        ),
        migrations.CreateModel(
            name='PlaySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setName', models.CharField(default='default', max_length=100)),
                ('plays', models.ManyToManyField(blank=True, to='ExhibitPage.play')),
            ],
        ),
        migrations.AddField(
            model_name='exhibitdata',
            name='playSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExhibitPage.playset'),
        ),
    ]
