# Generated by Django 4.2.9 on 2024-02-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playName', models.CharField(max_length=200)),
                ('playDescription', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(max_length=200)),
                ('descText', models.CharField(max_length=200)),
                ('imagePath', models.CharField(max_length=200)),
                ('exhibitPlays', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ExhibitPage.playtypes')),
            ],
        ),
    ]
