# Generated by Django 5.0.1 on 2024-01-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(max_length=200)),
                ('descText', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ExDescription',
        ),
    ]
