# Generated by Django 4.2.9 on 2024-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitPage', '0002_extext_delete_exdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='extext',
            name='imagePath',
            field=models.CharField(default='/test.png', max_length=200),
            preserve_default=False,
        ),
    ]
