# Generated by Django 4.2.9 on 2024-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitPage', '0002_remove_exhibitdata_imagepath_exhibitdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitdata',
            name='image',
            field=models.ImageField(default='blank', upload_to='images'),
        ),
    ]
