# Generated by Django 4.2.9 on 2024-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitPage', '0003_remove_play_votes_alter_extext_desctext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='playSet',
        ),
        migrations.AddField(
            model_name='playtypes',
            name='plays',
            field=models.ManyToManyField(blank=True, to='ExhibitPage.play'),
        ),
    ]
