#This File was generated by Django and modified by: Kevin Panasiuk
#Log:
#4/1/24: Made this header.

from django.contrib import admin

from .models import ExhibitData, Play, PlaySet, Vote

admin.site.register(ExhibitData)
admin.site.register(Play)
admin.site.register(PlaySet)
admin.site.register(Vote)