# Generated by Django 4.2.9 on 2024-02-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='playSet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ExhibitPage.playtypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playtypes',
            name='setName',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='extext',
            name='descText',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='extext',
            name='imagePath',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='extext',
            name='titleText',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='play',
            name='playDescription',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='play',
            name='playName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
