# Generated by Django 4.2.9 on 2024-04-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutText',
            new_name='ContactText',
        ),
    ]
