#This File was generated by Django and modified by: Kevin Panasiuk
#Log:
#4/1/24: Made this header.

from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]