"""
Django settings for GlazerMuseumApp project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()
# Basic configurations
ALLOWED_HOSTS = ['127.0.0.1']

# Security settings
SECURE_SSL_REDIRECT = True

# Set HTTP Strict Transport Security (HSTS) to enforce HTTPS on all connections.
# This tells browsers to remember that the site should only be accessed using HTTPS.
SECURE_HSTS_SECONDS = 31536000  # 1 year

# Include subdomains in the HSTS policy to ensure all subdomains are also accessed via HTTPS.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Allow the HSTS policy to be included in browsers' preload lists.
# This makes it more effective against SSL stripping attacks.
SECURE_HSTS_PRELOAD = True

# Marks the session cookie as secure, instructing browsers to only send it via HTTPS.
SESSION_COOKIE_SECURE = True

# Marks the CSRF cookie as secure, instructing browsers to only send it via HTTPS.
# This reduces the risk of interception in non-secure environments.
CSRF_COOKIE_SECURE = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ExhibitPage.apps.ExhibitpageConfig',
    'SplashPage.apps.SplashpageConfig',
    'Login.apps.LoginConfig',
    'About.apps.AboutConfig',
    'Contact.apps.ContactConfig',
    'Report.apps.ReportConfig',
    #Admin Honeypot app
    'admin_honeypot',
    #2FA
    'django_otp',
    'django_otp.plugins.otp_totp',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #verify the cookies uniquely
    'ExhibitPage.verification.VerifyUser', 
     #2FA stuff
    'django_otp.middleware.OTPMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GlazerMuseumApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GlazerMuseumApp.wsgi.application'




# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
#timezone that supports daylight savings(Do not change it will mess up 2fa):
TIME_ZONE = 'EST5EDT'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')

MEDIA_URL = ''

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
